# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='catgroy',
            field=models.CharField(choices=[('gx', '高校'), ('gr', '个人'), ('pxjg', '培训机构')], default='pxjg', max_length=100),
        ),
    ]
