# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0003_auto_20170805_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='courses',
            field=models.CharField(default='', max_length=100, verbose_name='经典课程'),
        ),
    ]
