# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0004_courseorg_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='address',
        ),
    ]
