# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0008_auto_20170807_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='courses_nums',
            field=models.IntegerField(default=1, max_length=20, verbose_name='课程数'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='courses',
            field=models.ForeignKey(default='1', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
