# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0010_userask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='courses_name',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='courses',
        ),
    ]
