# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0012_auto_20170811_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%M', verbose_name='教师照片'),
        ),
    ]
