# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20170810_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
