# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170810_1401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_auto_20170810_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('courses', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='courses.Courses', verbose_name='课程')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名字')),
            ],
        ),
    ]
