# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fa_type',
            field=models.CharField(choices=[(1, '课程'), (2, '讲师'), (3, '机构')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='favid',
            field=models.IntegerField(default=1, max_length=50, verbose_name='数据ID'),
        ),
    ]
