# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coureseresource_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureseresource',
            name='courses',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.Courses', verbose_name='课程'),
        ),
    ]
