# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_courses_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_nums',
            field=models.IntegerField(default=1, max_length=10, verbose_name='课程章节数'),
        ),
    ]
