# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_lesson_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(default='后端开发', max_length=50, verbose_name='课程类别'),
        ),
    ]
