# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teacher_tell',
            field=models.CharField(default='', max_length=100, verbose_name='老师告诉你能学到什么'),
        ),
        migrations.AddField(
            model_name='courses',
            name='you_know',
            field=models.CharField(default='', max_length=100, verbose_name='课程须知'),
        ),
    ]
