# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170802_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户信息哦', 'verbose_name_plural': '用户信息哦'},
        ),
    ]
