# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170811_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
