# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170902_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('updata', '修改邮箱')], max_length=10),
        ),
    ]
